import * as fs from 'fs'
import * as path from 'path'
import type { Skill } from './skills.js'
import { LLM_SKILL_MARKER } from './skills.js'

export const MOATLOG_SKILLS_START = '<!-- moatlog-skills-start -->'
export const MOATLOG_SKILLS_END = '<!-- moatlog-skills-end -->'

export const AGENTS_MD_STUB = `# Agent Behavioral Skills
Generated by moatlog — see moatlog.dev/docs

${MOATLOG_SKILLS_START}
${MOATLOG_SKILLS_END}
`

export function buildAgentsMdSkillsSection(skills: Skill[]): string {
  const header = [
    MOATLOG_SKILLS_START,
    '## Behavioral Skills',
    '',
    LLM_SKILL_MARKER,
    '',
    '> Auto-generated by moatlog from .moatlog/moat.json',
    '> Regenerate: `moatlog skills generate`',
    '',
    ''
  ].join('\n')

  const skillBlocks = skills
    .map(skill => {
      const coreFiles = skill.coreFiles.map(f => `- \`${f.path}\` (${f.pct}%)`).join('\n')
      return [
        `### ${skill.name}`,
        skill.description,
        '',
        `**When this applies:** ${skill.triggerDescription}`,
        '',
        '**Core files:**',
        coreFiles,
        '',
        `**Before starting:** ${skill.guidance}`,
        '',
        '---',
        ''
      ].join('\n')
    })
    .join('\n')

  return `${header}${skillBlocks}${MOATLOG_SKILLS_END}\n`
}

export function updateAgentsMdContent(existing: string | null, skills: Skill[]): string {
  const section = buildAgentsMdSkillsSection(skills)

  if (!existing) {
    return `# Agent Behavioral Skills
Generated by moatlog — see moatlog.dev/docs

${section}`
  }

  const startIdx = existing.indexOf(MOATLOG_SKILLS_START)
  const endIdx = existing.indexOf(MOATLOG_SKILLS_END)

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx)
    const after = existing.slice(endIdx + MOATLOG_SKILLS_END.length)
    return `${before}${section}${after}`.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
  }

  const suffix = existing.endsWith('\n') ? '' : '\n'
  return `${existing}${suffix}\n${section}`
}

export function hasAgentsMdSkillsSection(content: string): boolean {
  const startIdx = content.indexOf(MOATLOG_SKILLS_START)
  const endIdx = content.indexOf(MOATLOG_SKILLS_END)
  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) return false

  const between = content.slice(startIdx + MOATLOG_SKILLS_START.length, endIdx)
  return between.includes('## Behavioral Skills') && /###\s+\S+/.test(between)
}

export function writeAgentsMdSkills(projectRoot: string, skills: Skill[]): void {
  const agentsPath = path.join(projectRoot, 'AGENTS.md')
  const existing = fs.existsSync(agentsPath) ? fs.readFileSync(agentsPath, 'utf-8') : null
  fs.writeFileSync(agentsPath, updateAgentsMdContent(existing, skills))
}
